services:
  judge-backend:
    build: ./src/backend
    container_name: judge-backend
    working_dir: /app
    environment:
      - ASPNETCORE_URLS=http://0.0.0.0:8001
      - ConnectionStrings__Default=Host=${DB_HOST};Port=${DB_PORT};Username=${DB_USER};Password=${DB_PASSWORD};Database=${DB_NAME}
      
    ports:
      - "8001:8001"
    volumes:
      - ./src/backend:/app
    command: sh -c "dotnet watch run --project WebBackend --no-launch-profile"
  judge-frontend:
    build: ./src/frontend
    container_name: judge-frontend
    working_dir: /app
    ports:
      - "3000:3000"
    volumes:
      - ./src/frontend:/app
      - /app/node_modules
      - /app/.next
    environment:
      - BACKEND_URL=http://judge-backend:8001
    command: npm run dev
  judge-db:
    build: ./src/db
    container_name: judge-db
    working_dir: /app
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5435:5432"